# Providing all tests pass then changes to the following branches are automatically deployed to the respective environment:-
# `develop` -> Develop environment
# `release/**` -> Staging environment
# `hotfix/**` -> Production environment
# `master` -> Production environment
# @TODO include tests!
version: 2.1
executors:
  default:
    docker:
      - image: circleci/node:10.16.0-stretch
    working_directory: ~/digital-platform

jobs:
  setup:
    executor: default
    steps:
      - checkout
      - run:
          name: 'Setup'
          command: npm ci
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    executor: default
    steps:
      - attach_workspace:
          at: ~/digital-platform
      - run:
          name: 'Lint'
          command: npm run lint-ci
      # - run:
      #     name: 'Test'
      #     command: npm run test-ci

  build-and-deploy-production:
    executor: default
    steps:
      - attach_workspace:
          at: ~/digital-platform
      - run:
          name: 'Deploy to production'
          command: |
            npm run production:build
            node_modules/.bin/firebase target:apply hosting production-assessments-app jac-assessments --project production 
            node_modules/.bin/firebase deploy --force --token=$FIREBASE_DEPLOY_TOKEN --only hosting:production-assessments-app --project production

  build-and-deploy-staging:
    executor: default
    steps:
      - attach_workspace:
          at: ~/digital-platform
      - run:
          name: 'Deploy to staging'
          command: |
            npm run staging:build
            node_modules/.bin/firebase target:apply hosting staging-assessments-app jac-assessments-staging --project staging
            node_modules/.bin/firebase deploy --force --token=$FIREBASE_DEPLOY_TOKEN --only hosting:staging-assessments-app --project staging

  build-and-deploy-develop:
    executor: default
    steps:
      - attach_workspace:
          at: ~/digital-platform
      - run:
          name: 'Deploy to develop'
          command: |
            npm run develop:build
            node_modules/.bin/firebase target:apply hosting develop-assessments-app jac-assessments-develop --project develop
            node_modules/.bin/firebase deploy --force --token=$FIREBASE_DEPLOY_TOKEN --only hosting:develop-assessments-app --project develop

workflows:
  version: 2
  test-build-and-deploy:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build-and-deploy-develop:
          requires:
            - test
          filters:
            branches:
              only: /develop/
      - build-and-deploy-staging:
          requires:
            - test
          filters:
            branches:
              only: /release/.*/
      - build-and-deploy-production:
          requires:
            - test
          filters:
            branches:
              only: 
                - master
                - /hotfix/.*/
